Repository BbobaVoca/BbobaVoca, pull requests merged in 2024-06, with the labels that each got.

#58 Fix: 로그인/회원가입 페이지에서 헤더 컴포넌트에 로고만 보이게
  frontend/src/components/Navbars.tsx
Labels: Design

#59 Feat/#57/printer
  frontend/src/api/bbobavoca/bbobavocaAxios.ts
  frontend/src/components/MyInfoCard.tsx
  frontend/src/components/PrintSection.tsx
  frontend/src/pages/MyPage.tsx
  frontend/src/styles/font/온글잎 의청수 시우체.ttf
Labels: fix, Feat

#60 Feat/#57/printer
  frontend/src/components/PrintSection.tsx
Labels: fix, Feat, Design
